### ISSUE TITLE
react-native-pos-printer:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by davmaene** [bencomtech/react-native-pos-printer#4]
hello, I am trying to build the application but I am faced with this error
```react-native-pos-printer\android\src\main\java\com\reactlibrary\printer\printing\PrinterUtils.java:10:error: package android.support.v4.content does not exist import android.support.v4.content.ContextCompat; ```

can get any support please, my project's infos
```
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
```

**Comment by tour-panurat** [comment]
try install androidx in your project
and use `import androidx.core.content.ContextCompat;`

**Comment by davmaene** [comment]
Thank you, i finaly resolved the issue, now i'm able to print on device ( POS Z91 ),
